### PR TITLE
correct issue getHistoricalQuoteData-start-to-give-401-unauthorized-#52

### PR DESCRIPTION
**Pull request by jrodriguesd**
**Description**

### CODE REVIEW

**Comment by scheb** [comment]
Would you have a look at the code style issues? Is guess running php-cs-fixer would likely solve half of it.

**Comment by jrodriguesd** [comment]
Dear Sir. I don't know how to solve Codecov Issue. Best regards

**Comment by scheb** [comment]
Looks good! From what I can see, the method `private function getHistoricalDataResponseBody` seems to be dead code and should be removed. (Or you put your implementation in there and remove the `getHistoricalDataResponseBodyJson` method. However you like).

The `historicalData.csv`, `dividendData.csv` and `splitData.csv` fixture files should also be removed, since it's no longer needed.

You can't do anything about the Codecov issue, you don't need to worry about that.

**Comment by jrodriguesd** [comment]
Dear Sir. Ready. 

    Thank you for your guidance. 
    Do I need to create another PR?

    Best Regards

**Comment by scheb** [comment]
Thank you for solving this issue! A lot of people are going to love this.

Release as v4.11.0.

**Pull request merged**
