### PR TITLE
Added possibility to search in other regions

### PR DESCRIPTION
**Pull request by BenjaminPaap**
**Description**
We need to search for searchTerms in other regions than only the US. You can provide a region to the Yahoo Finance API in order to get other results. Added a possibility to specify a region but did not break any logic.

### CODE REVIEW

**Comment by scheb** [comment]
Please check the syntax error on PHP 7.1 in the build. Besides that, looks good to me.

**Comment by BenjaminPaap** [comment]
> Please check the syntax error on PHP 7.1 in the build. Besides that, looks good to me.

Updated PR. Thanks for the hint.

**Comment by scheb** [comment]
Thanks for contributing. Released as v4.3.0.

**Comment by BenjaminPaap** [comment]
Nice, thanks!

**Pull request merged**
